POST http://localhost:3001/signup
Content-Type: application/json

{"username": "nafi", "password": "1234"}

### 

POST http://localhost:3001/login
Content-Type: application/json

{"username": "kz", "password": "Ketu2"}


### 

POST http://localhost:3001/logout
Content-Type: application/json

{"username": "kz", "password": ""}

### 

GET http://localhost:3001/dashboard/kz
Content-Type: application/json

{ "token": "eyJhbGiOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imt6IiwiaWF0IjoxNzI2MjU0NDkyLCJleHAiOjE3MjYyNTUwOTJ9.r2azHITzRRF_-cdqm1s4TAgBucziHIwbMpRnrN4l1dA" }


###

GET http://localhost:3001/med
Content-Type: application/json
Cookie: cooks=2