###
GET http://localhost:3001/meds
Content-Type: application/json
Cookie: a_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hZmkiLCJpYXQiOjE3MjY3NTE3NTYsImV4cCI6MTcyNjc1MTc4Nn0.Y9cPnUxegb1MczJiJ-ycilamNd9xRVof57bJp94FUbQ; r_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hZmkiLCJpYXQiOjE3MjY3NTE3NTYsImV4cCI6MTcyOTM0Mzc1Nn0.UsbgKf3SkSV90FDkcvxRiO1PORuZIilhIR6qCYI8Xpw;